name: app
description: A new Flutter project.
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  http: ^1.1.0
  keep_screen_on: ^3.0.0
  mocktail: ^1.0.3
  mqtt_client: ^10.2.0
  network_info_plus: ^4.1.0+1
  path_provider: ^2.1.2
  riverpod_annotation: ^3.0.0-dev.3

  video_player: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner:
  custom_lint:
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  typed_data: ^1.3.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
